/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package watersys.UI;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import watersys.DAO.NhanVienDAO;
import watersys.Entity.NhanVien;
import watersys.Utilities.MsgBox;
import watersys.Utilities.XImage;

/**
 *
 * @author xuanc
 */
public class QuenMK extends javax.swing.JDialog {

    /**
     * Creates new form QuenMK
     */
    public QuenMK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    void init() {
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("CẤP LẠI MẬT KHẨU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnQuenMK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/watersys/Icon/dsBuffer.bmp.png"))); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnQuenMK.setBackground(new java.awt.Color(0, 0, 153));
        btnQuenMK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQuenMK.setForeground(new java.awt.Color(255, 255, 255));
        btnQuenMK.setText("Cấp lại mật khẩu");
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Nhập email nhận mật khẩu của nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 199, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(232, 232, 232))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateForm(boolean chk) {
        if (txtEmail.getText().length() == 0) {
            MsgBox.alert(this, "Bạn chưa nhập Email!");
            txtEmail.requestFocus();
            return false;
        } else if (!txtEmail.getText().matches("\\w+@\\w+(\\.\\w+){1,2}")) {
            MsgBox.alert(this, "Email không đúng định dạng!");
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }
    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMKActionPerformed
        if (validateForm(true)) {
            String email = txtEmail.getText(); // Lấy địa chỉ email từ trường nhập liệu
            NhanVienDAO nhanVienDAO = new NhanVienDAO();
            NhanVien nhanVien = nhanVienDAO.selectByEmail(email);

            if (nhanVien != null) {
                String to = email; // Địa chỉ email của nhân viên
                String subject = "Cấp lại mật khẩu";
                String password = nhanVien.getMatKhau(); // Lấy mật khẩu từ đối tượng NhanVien
                String MaNV = nhanVien.getMaNV();

                // Sử dụng mã gửi email của bạn để gửi mật khẩu qua email
                try {
                    Properties p = new Properties();
                    p.put("mail.smtp.auth", "true");
                    p.put("mail.smtp.starttls.enable", "true");
                    p.put("mail.smtp.host", "smtp.gmail.com");
                    p.put("mail.smtp.port", 587);

                    String accountName = "xuanchient033@gmail.com";
                    String accountPassword = "cxnd teoe jlrc kkce";

                    Session s = Session.getInstance(p, new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(accountName, accountPassword);
                        }
                    });

                    String from = accountName;
                    String body ="Mã nhân viên của bạn: " + MaNV + "\nMật khẩu của bạn là: " + password;

                    Message msg = new MimeMessage(s);
                    msg.setFrom(new InternetAddress(from));
                    msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
                    msg.setSubject(subject);
                    msg.setText(body);

                    Transport.send(msg);
                    MsgBox.alert(this, "Mật khẩu đã được gửi tới email của nhân viên");
                } catch (MessagingException ex) {
                    MsgBox.alert(this, "Gửi email thất bại. Vui lòng thử lại sau.");
                }
            } else {
                MsgBox.alert(this, "Email không tồn tại trong cơ sở dữ liệu. Hãy kiểm tra lại.");
                // Yêu cầu người dùng nhập lại email hoặc thực hiện hành động khác
                txtEmail.requestFocusInWindow();
            }

        }

//        String taiKHoan = txtTaiKhoan.getText();
//        NhanVien nhanVien = nhanVienDAO.selectByTaiKhoan(taiKHoan);
//
//            // Lấy địa chỉ email từ đối tượng NhanVien
//            String to = nhanVien.getEmail();
//
//            // Sử dụng thông tin nhân viên đã truy vấn từ cơ sở dữ liệu
//            String subject = "Cấp lại mật khẩu";
//            String password = nhanVien.getMatKhau();
//
//            // Thực hiện gửi email như trong mã trước đó
//            try {
//                Properties p = new Properties();
//                p.put("mail.smtp.auth", "true");
//                p.put("mail.smtp.starttls.enable", "true");
//                p.put("mail.smtp.host", "smtp.gmail.com");
//                p.put("mail.smtp.port", 587);
//
//                String accountName = "xuanchient033@gmail.com";
//                String accountPassword = "cxnd teoe jlrc kkce";
//
//                Session s = Session.getInstance(p, new javax.mail.Authenticator() {
//                    protected PasswordAuthentication getPasswordAuthentication() {
//                        return new PasswordAuthentication(accountName, accountPassword);
//                    }
//                });
//
//                String from = accountName;
//                String body = "mật khẩu của bạn là " + password;
//
//                Message msg = new MimeMessage(s);
//                msg.setFrom(new InternetAddress(from));
//                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
//                msg.setSubject(subject);
//                msg.setText(body);
//
//                Transport.send(msg);
//                MsgBox.alert(this, "Mật khẩu đã được gửi tới email của nhân viên");
//            } catch (MessagingException ex) {
//                //            MsgBox.alert(this, "đổi mật khẩu thất bại");
//                System.out.println(ex);
//            }
    }//GEN-LAST:event_btnQuenMKActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMK dialog = new QuenMK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
